public class rohith {
    
    public static void kiran(Account Acc,list<Account>Acclist){
        if(Acc.Id !=null){
        example();
        }
        else if(Acc.Name=='sai'){
        sai.ravi();
        }
        else{
            
        }
        for(Account Acc2 :Acclist){
            if(Acc2.Name =='subha'){
                
            }         
        }
        
    }
    public static void example(){
        
    }

}